// CifAndroidBootstrap.cs — add to the same GameObject as CrystalCIFViewer.
//
// On Android (Meta Quest), StreamingAssets lives inside the compressed APK where System.IO
// cannot read it. This bootstrap copies the bundled CIFs (listed in
// StreamingAssets/CIF/manifest.txt, regenerated by CifLibrarySync before every build) into
// persistentDataPath/CIF via UnityWebRequest, after which the file-based library scan finds them.
//
// • First launch of each new build (keyed on Application.buildGUID) re-copies every file, so
//   edited CIFs update; later launches only fill in anything missing.
// • Files no longer in the manifest are pruned from that folder (it is ours alone).
// • LibraryReady fires when done so an already-open library UI can refresh.
// On desktop platforms and in the editor this component does nothing.

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Networking;

public class CifAndroidBootstrap : MonoBehaviour
{
    /// <summary>Raised once the bundled CIF library has been copied to readable storage.</summary>
    public static event Action LibraryReady;

    private const string VersionFile = ".build";

    private IEnumerator Start()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        string srcRoot = Path.Combine(Application.streamingAssetsPath, "CIF");
        string dstRoot = Path.Combine(Application.persistentDataPath, "CIF");
        Directory.CreateDirectory(dstRoot);

        string manifestText;
        using (var req = UnityWebRequest.Get(Path.Combine(srcRoot, "manifest.txt")))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogWarning($"[CifBootstrap] No CIF manifest in StreamingAssets: {req.error}");
                yield break;
            }
            manifestText = req.downloadHandler.text;
        }

        var names = new List<string>();
        foreach (var raw in manifestText.Split('\n'))
        {
            string name = raw.Trim();
            if (name.Length > 0 && !name.StartsWith("#")) names.Add(name);
        }

        // New build installed? Then refresh every file, not just the missing ones.
        string versionPath = Path.Combine(dstRoot, VersionFile);
        string stamp = Application.buildGUID;
        bool newBuild = !File.Exists(versionPath) || File.ReadAllText(versionPath) != stamp;

        int copied = 0;
        foreach (var name in names)
        {
            string dst = Path.Combine(dstRoot, name);
            if (!newBuild && File.Exists(dst)) continue;

            using (var fileReq = UnityWebRequest.Get(Path.Combine(srcRoot, name)))
            {
                yield return fileReq.SendWebRequest();
                if (fileReq.result == UnityWebRequest.Result.Success)
                {
                    File.WriteAllBytes(dst, fileReq.downloadHandler.data);
                    copied++;
                }
                else
                {
                    Debug.LogWarning($"[CifBootstrap] Failed to copy {name}: {fileReq.error}");
                }
            }
        }

        // Prune structures that were removed from the project.
        var keep = new HashSet<string>(names, StringComparer.OrdinalIgnoreCase) { VersionFile };
        foreach (var existing in Directory.GetFiles(dstRoot))
            if (!keep.Contains(Path.GetFileName(existing)))
                try { File.Delete(existing); } catch { }

        File.WriteAllText(versionPath, stamp);
        Debug.Log($"[CifBootstrap] Library ready: {names.Count} structures ({copied} copied).");
        LibraryReady?.Invoke();
#else
        // Desktop/editor read StreamingAssets directly — the library is ready immediately.
        LibraryReady?.Invoke();
        yield break;
#endif
    }
}
