// CifLibrarySync.cs — keeps the shipped CIF library in step with Assets/GameObjects.
//
// Only Assets/StreamingAssets ships inside a player build, so CIFs dropped into
// Assets/GameObjects are invisible on Quest/desktop builds unless copied over. This runs
// automatically before every build (and from Tools ▸ Crystallography ▸ Sync CIF Library):
//   • copies every valid CIF (.cif, or .txt containing CIF tags) from Assets/GameObjects into
//     Assets/StreamingAssets/CIF (new or changed files only)
//   • rewrites StreamingAssets/CIF/manifest.txt, which CifAndroidBootstrap uses on Quest

using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

public class CifLibrarySync : IPreprocessBuildWithReport
{
    private const string SourceDir = "Assets/GameObjects";
    private const string TargetDir = "Assets/StreamingAssets/CIF";
    private const string Manifest  = "manifest.txt";

    public int callbackOrder => 0;

    public void OnPreprocessBuild(BuildReport report) => Sync(logSummary: true);

    [MenuItem("Tools/Crystallography/Sync CIF Library")]
    private static void SyncMenu()
    {
        Sync(logSummary: true);
        AssetDatabase.Refresh();
    }

    public static void Sync(bool logSummary)
    {
        Directory.CreateDirectory(TargetDir);

        int copied = 0;
        if (Directory.Exists(SourceDir))
        {
            foreach (var src in Directory.GetFiles(SourceDir))
            {
                if (!IsCif(src)) continue;
                string dst = Path.Combine(TargetDir, Path.GetFileName(src));
                if (File.Exists(dst) && FilesEqual(src, dst)) continue;
                File.Copy(src, dst, overwrite: true);
                copied++;
            }
        }

        var names = Directory.GetFiles(TargetDir)
            .Where(IsCif)
            .Select(p => Path.GetFileName(p))
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();

        File.WriteAllLines(Path.Combine(TargetDir, Manifest),
            new[]
            {
                "# Bundled CIF structures — one file name per line.",
                "# Auto-generated by CifLibrarySync (Editor) before every build; CifAndroidBootstrap copies these on Quest.",
            }.Concat(names));

        if (logSummary)
            Debug.Log($"[CifLibrarySync] {names.Count} structures in {TargetDir} ({copied} new/updated from {SourceDir}).");
    }

    private static bool IsCif(string path)
    {
        string name = Path.GetFileName(path);
        if (name.Equals(Manifest, StringComparison.OrdinalIgnoreCase)) return false;
        string ext = Path.GetExtension(path).ToLowerInvariant();
        if (ext == ".cif") return true;
        if (ext != ".txt") return false;
        try
        {
            foreach (var line in File.ReadLines(path).Take(120))
                if (line.Contains("_cell_length") || line.Contains("_atom_site")) return true;
        }
        catch { }
        return false;
    }

    private static bool FilesEqual(string a, string b)
    {
        var fa = new FileInfo(a); var fb = new FileInfo(b);
        return fa.Length == fb.Length && File.ReadAllBytes(a).SequenceEqual(File.ReadAllBytes(b));
    }
}
